
// pack structures, no padding for 8-bit or 16-bit types
#pragma pack(2)

#include "clib/compiler-specific.h"

// structs and constants

#include "exec/exec.h"

#include "classes/arexx.h"
#include "classes/requester.h"
#include "classes/window.h"

#include "datatypes/animationclass.h"
#include "datatypes/datatypes.h"
#include "datatypes/datatypesclass.h"
#include "datatypes/pictureclass.h"
#include "datatypes/soundclass.h"
#include "datatypes/textclass.h"

#include "devices/audio.h"
#include "devices/bootblock.h"
#include "devices/cd.h"
#include "devices/clipboard.h"
#include "devices/console.h"
#include "devices/conunit.h"
#include "devices/gameport.h"
#include "devices/hardblocks.h"
#include "devices/input.h"
#include "devices/inputevent.h"
#include "devices/keyboard.h"
#include "devices/keymap.h"
#include "devices/narrator.h"
#include "devices/newstyle.h"
#include "devices/parallel.h"
#include "devices/printer.h"
#include "devices/prtbase.h"
#include "devices/prtgfx.h"
#include "devices/scsidisk.h"
#include "devices/serial.h"
#include "devices/timer.h"
#include "devices/trackdisk.h"
#include "devices/trackfile.h"

#include "diskfont/diskfont.h"
#include "diskfont/diskfonttag.h"
#include "diskfont/glyph.h"
#include "diskfont/oterrors.h"

#include "dos/ansiio.h"
#include "dos/datetime.h"
#include "dos/dos.h"
#include "dos/dosasl.h"
#include "dos/dosextens.h"
#include "dos/doshunks.h"
#include "dos/dostags.h"
#include "dos/exall.h"
#include "dos/filehandler.h"
#include "dos/notify.h"
#include "dos/rdargs.h"
#include "dos/record.h"
#include "dos/shell.h"
#include "dos/stdio.h"
#include "dos/var.h"

#include "gadgets/button.h"
#include "gadgets/checkbox.h"
#include "gadgets/chooser.h"
#include "gadgets/clicktab.h"
#include "gadgets/colorwheel.h"
#include "gadgets/datebrowser.h"
#include "gadgets/fuelgauge.h"
#include "gadgets/getcolor.h"
#include "gadgets/getfile.h"
#include "gadgets/getfont.h"
#include "gadgets/getscreenmode.h"
#include "gadgets/gradientslider.h"
#include "gadgets/integer.h"
#include "gadgets/layout.h"
#include "gadgets/listbrowser.h"
#include "gadgets/listview.h"
#include "gadgets/page.h"
#include "gadgets/palette.h"
#include "gadgets/radiobutton.h"
#include "gadgets/scroller.h"
#include "gadgets/sketchboard.h"
#include "gadgets/slider.h"
#include "gadgets/space.h"
#include "gadgets/speedbar.h"
#include "gadgets/string.h"
#include "gadgets/tabs.h"
#include "gadgets/tapedeck.h"
#include "gadgets/texteditor.h"
#include "gadgets/virtual.h"
#include "graphics/clip.h"
#include "graphics/coerce.h"
#include "graphics/collide.h"
#include "graphics/copper.h"
#include "graphics/display.h"
#include "graphics/displayinfo.h"
#include "graphics/gels.h"
#include "graphics/gfx.h"
#include "graphics/gfxbase.h"
#include "graphics/gfxmacros.h"
#include "graphics/gfxnodes.h"
#include "graphics/graphint.h"
#include "graphics/layers.h"
#include "graphics/modeid.h"
#include "graphics/monitor.h"
#include "graphics/rastport.h"
#include "graphics/regions.h"
#include "graphics/rpattr.h"
#include "graphics/scale.h"
#include "graphics/sprite.h"
#include "graphics/text.h"
#include "graphics/videocontrol.h"
#include "graphics/view.h"

#include "hardware/adkbits.h"
#include "hardware/blit.h"
#include "hardware/cia.h"
#include "hardware/custom.h"
#include "hardware/dmabits.h"
#include "hardware/intbits.h"

#include "images/bevel.h"
#include "images/bitmap.h"
#include "images/drawlist.h"
#include "images/glyph.h"
#include "images/label.h"
#include "images/led.h"
#include "images/penmap.h"

#include "intuition/cghooks.h"
#include "intuition/classes.h"
#include "intuition/classusr.h"
#include "intuition/gadgetclass.h"
#include "intuition/icclass.h"
#include "intuition/imageclass.h"
#include "intuition/intuition.h"
#include "intuition/intuitionbase.h"
#include "intuition/iobsolete.h"
#include "intuition/pointerclass.h"
#include "intuition/preferences.h"
#include "intuition/screens.h"
#include "intuition/sghooks.h"

#include "libraries/amigaguide.h"
#include "libraries/asl.h"
#include "libraries/commodities.h"
#include "libraries/configregs.h"
#include "libraries/configvars.h"
#include "libraries/diskfont.h"
#include "libraries/diskfonttag.h"
#include "libraries/dos.h"
#include "libraries/dosextens.h"
#include "libraries/expansion.h"
#include "libraries/expansionbase.h"
#include "libraries/filehandler.h"
#include "libraries/gadtools.h"
#include "libraries/iffparse.h"
#include "libraries/keymap.h"
#include "libraries/locale.h"
#include "libraries/lowlevel.h"
#include "libraries/mathffp.h"

// disabled: mathieeedp.h contains only macro redefinitions for the mathieeedoubbas functions
//#include "libraries/mathieeedp.h"
// disabled: mathieeesp.h contains only macro redefinitions for the mathieeesingbas functions
//#include "libraries/mathieeesp.h"

#include "libraries/mathlibrary.h"
#include "libraries/mathresource.h"
#include "libraries/nonvolatile.h"
#include "libraries/realtime.h"
#include "libraries/translator.h"

#include "prefs/asl.h"
#include "prefs/font.h"
#include "prefs/icontrol.h"
#include "prefs/input.h"
#include "prefs/locale.h"
#include "prefs/overscan.h"
#include "prefs/palette.h"
#include "prefs/pointer.h"
#include "prefs/prefhdr.h"
#include "prefs/printergfx.h"
#include "prefs/printerps.h"
#include "prefs/printertxt.h"
#include "prefs/reaction.h"
#include "prefs/screenmode.h"
#include "prefs/serial.h"
#include "prefs/sound.h"
#include "prefs/wbpattern.h"
#include "prefs/workbench.h"

#include "reaction/reaction.h"
#include "reaction/reaction_author.h"
#include "reaction/reaction_class.h"
#include "reaction/reaction_macros.h"
#include "reaction/reaction_prefs.h"

#include "resources/battclock.h"
#include "resources/battmem.h"
#include "resources/battmembitsamiga.h"
#include "resources/battmembitsamix.h"
#include "resources/battmembitsshared.h"
#include "resources/card.h"
#include "resources/cia.h"
#include "resources/ciabase.h"
#include "resources/disk.h"
#include "resources/filesysres.h"
#include "resources/mathresource.h"
#include "resources/misc.h"
#include "resources/potgo.h"

#include "rexx/errors.h"
#include "rexx/rexxio.h"
#include "rexx/rxslib.h"
#include "rexx/storage.h"

#include "utility/date.h"
#include "utility/hooks.h"
#include "utility/name.h"
#include "utility/pack.h"
#include "utility/tagitem.h"
#include "utility/utility.h"

#include "workbench/icon.h"
#include "workbench/startup.h"
#include "workbench/workbench.h"

// functions

// no stdio functions or functions implemented in amiga.lib
//#include "clib/alib_protos.h"
//#include "clib/alib_stdio_protos.h"
//#include "clib/all_protos.h"
#include "clib/amigaguide_protos.h"
#include "clib/arexx_protos.h"
#include "clib/asl_protos.h"
#include "clib/battclock_protos.h"
#include "clib/battmem_protos.h"
#include "clib/bevel_protos.h"
#include "clib/bitmap_protos.h"
#include "clib/bullet_protos.h"
#include "clib/button_protos.h"
#include "clib/cardres_protos.h"
#include "clib/checkbox_protos.h"
#include "clib/chooser_protos.h"
#include "clib/cia_protos.h"
#include "clib/clicktab_protos.h"
#include "clib/colorwheel_protos.h"
#include "clib/commodities_protos.h"
#include "clib/compiler-specific.h"
#include "clib/console_protos.h"
#include "clib/datatypes_protos.h"
#include "clib/datebrowser_protos.h"
// no debug functions implemented in amiga.lib
//#include "clib/ddebug_protos.h"
//#include "clib/debug_protos.h"
#include "clib/disk_protos.h"
#include "clib/diskfont_protos.h"
#include "clib/dos_protos.h"
#include "clib/drawlist_protos.h"
#include "clib/exec_protos.h"
#include "clib/expansion_protos.h"
#include "clib/fuelgauge_protos.h"
#include "clib/gadtools_protos.h"
#include "clib/getcolor_protos.h"
#include "clib/getfile_protos.h"
#include "clib/getfont_protos.h"
#include "clib/getscreenmode_protos.h"
#include "clib/glyph_protos.h"
#include "clib/graphics_protos.h"
#include "clib/icon_protos.h"
#include "clib/iffparse_protos.h"
#include "clib/input_protos.h"
#include "clib/integer_protos.h"
#include "clib/intuition_protos.h"
#include "clib/keymap_protos.h"
#include "clib/label_protos.h"
#include "clib/layers_protos.h"
#include "clib/layout_protos.h"
#include "clib/listbrowser_protos.h"
#include "clib/locale_protos.h"
#include "clib/lowlevel_protos.h"
// no macros (contains only few irrelevant macros)
//#include "clib/macros.h"
#include "clib/mathffp_protos.h"
#include "clib/mathieeedoubbas_protos.h"
#include "clib/mathieeedoubtrans_protos.h"
#include "clib/mathieeesingbas_protos.h"
#include "clib/mathieeesingtrans_protos.h"
#include "clib/mathtrans_protos.h"
#include "clib/misc_protos.h"
#include "clib/nonvolatile_protos.h"
#include "clib/palette_protos.h"
#include "clib/penmap_protos.h"
#include "clib/potgo_protos.h"
#include "clib/radiobutton_protos.h"
#include "clib/ramdrive_protos.h"
// sfd/fd entries are not found for reaction_lib
//#include "clib/reaction_lib_protos.h"
#include "clib/realtime_protos.h"
#include "clib/requester_protos.h"
#include "clib/rexxsyslib_protos.h"
#include "clib/scroller_protos.h"
#include "clib/sketchboard_protos.h"
#include "clib/slider_protos.h"
#include "clib/space_protos.h"
#include "clib/speedbar_protos.h"
#include "clib/string_protos.h"
#include "clib/texteditor_protos.h"
#include "clib/timer_protos.h"
#include "clib/trackfile_protos.h"
#include "clib/translator_protos.h"
#include "clib/utility_protos.h"
#include "clib/virtual_protos.h"
#include "clib/wb_protos.h"
#include "clib/window_protos.h"

// items missing in NDK headers

Class *LISTVIEW_GetClass( VOID );
